name: Deploy Hugo
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # 关键！确保主题能加载
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - run: hugo  # 生成静态文件
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public